# Generated by Django 3.1.2 on 2020-10-07 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=30)),
                ('descripton', models.TextField()),
                ('pub_date', models.DateField(verbose_name='date published')),
                ('status', models.CharField(choices=[('Done', 'Done'), ('Pending', 'Pending')], max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(verbose_name='date published')),
                ('status', models.CharField(choices=[('Done', 'Done'), ('Pending', 'Pending')], max_length=120)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.task')),
            ],
        ),
    ]
