# Generated by Django 3.1.2 on 2020-10-07 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_issue_issue_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="descripton",
            new_name="description",
        ),
    ]
