# Generated by Django 3.1.2 on 2020-10-16 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_auto_20201012_1457"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="issue",
            options={"ordering": ["-pub_date"]},
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-pub_date"]},
        ),
        migrations.AlterField(
            model_name="issue",
            name="pub_date",
            field=models.DateField(auto_now_add=True, verbose_name="date published"),
        ),
        migrations.AlterField(
            model_name="task",
            name="pub_date",
            field=models.DateField(auto_now_add=True, verbose_name="date published"),
        ),
    ]
